DROP TABLE IF EXISTS detale_tiekejas CASCADE;
DROP TABLE IF EXISTS uzsakymo_eilute CASCADE;
DROP TABLE IF EXISTS atsiliepimas CASCADE;
DROP TABLE IF EXISTS uzsakymas CASCADE;
DROP TABLE IF EXISTS detale CASCADE;
DROP TABLE IF EXISTS kategorija CASCADE;
DROP TABLE IF EXISTS tiekejas CASCADE;
DROP TABLE IF EXISTS klientas CASCADE;